services:
  mysql:
    image: mysql:8.0
    container_name: caringu-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: [
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci"
    ]
    networks:
      - vitalis-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  python:
    build:
      context: ./caringu-python
      dockerfile: Dockerfile
    container_name: caringu-python
    ports:
      - "8000:8000"
    networks:
      - vitalis-net
    restart: always

  spring:
    build:
      context: ./caringu-backend
      dockerfile: Dockerfile
    container_name: caringu-spring
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - IP_HOST=caringu-mysql
      - SPRING_MAIL_USERNAME=${SPRING_MAIL_USERNAME}
      - SPRING_MAIL_PASSWORD=${SPRING_MAIL_PASSWORD}
      - JWT_VALIDITY=${JWT_VALIDITY}
      - JWT_SECRET=${JWT_SECRET}
      - CONNECTION_STRING=${CONNECTION_STRING}
      - CONTAINER_NAME=${CONTAINER_NAME}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    ports:
      - "8080:8080"
    networks:
      - vitalis-net
    depends_on:
      mysql:
        condition: service_healthy
    restart: always

  frontend:
    build:
      context: ./caringu-frontend
      dockerfile: Dockerfile
    container_name: caringu-frontend
    ports:
      - "80:80"
    networks:
      - vitalis-net
    restart: always

volumes:
  mysql_data:

networks:
  vitalis-net:
    name: vitalis-net
    driver: bridge