services:
  mysql:
    image: mysql:8.0
    container_name: container-mysql-vitalis
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - vitalis-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
  python:
    build:
      context: ./caringu-python
      dockerfile: Dockerfile
    image: caringu-python:latest
    container_name: container-python-vitalis
    ports:
      - "8000:8000"
    networks:
      - vitalis-net
    restart: always

volumes:
  mysql_data:

networks:
  vitalis-net:
    driver: bridge