services:
  mysql:
    image: mysql:8.0
    container_name: caringu-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      LANG: C.UTF-8
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ../../db/creates-tables.sql:/docker-entrypoint-initdb.d/creates-tables.sql
      - ../../db/inserts.sql:/docker-entrypoint-initdb.d/inserts.sql
      - ../../db/insert-Outubro.sql:/docker-entrypoint-initdb.d/insert-Outubro.sql
    command: [
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci"
    ]
    networks:
      - caringu-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"    # porta do broker
      - "15672:15672"  # porta da interface web
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - caringu-network

  backend:
    build:
      context: ./caringu-backend
      dockerfile: Dockerfile
    container_name: caringu-backend
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      IP_HOST: caringu-mysql
      SPRING_MAIL_USERNAME: ${SPRING_MAIL_USERNAME}
      SPRING_MAIL_PASSWORD: ${SPRING_MAIL_PASSWORD}
      JWT_VALIDITY: ${JWT_VALIDITY}
      JWT_SECRET: ${JWT_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
      SPRING_PROFILES_ACTIVE: prod
      APP_RABBITMQ_EXCHANGE: notificacoes.exchange
    command: ["java", "-Xms512m", "-Xmx5g", "-Dspring.profiles.active=prod", "-jar", "/app/app.jar"]
    ports:
      - "8080:8080"
    networks:
      - caringu-network
    depends_on:
      rabbitmq:
        condition: service_healthy
      mysql:
        condition: service_healthy
    restart: always

  # Serviço que consome notificações
  notification-service:
    build:
      context: ./caringu-notificacao
      dockerfile: Dockerfile
    container_name: notification-service
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
      SPRING_PROFILES_ACTIVE: prod
      APP_RABBITMQ_EXCHANGE: notificacoes.exchange
      # Configurações do banco se este serviço também usar MySQL
      IP_HOST: caringu-mysql
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/vitalis?useSSL=false&serverTimezone=America/Sao_Paulo&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    command: ["java", "-Xms512m", "-Xmx5g", "-Dspring.profiles.active=prod", "-jar", "/app/app.jar"]
    ports:
      - "8081:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy
      mysql:
        condition: service_healthy
    networks:
      - caringu-network

volumes:
  mysql_data:

networks:
  caringu-network:
    name: caringu-network
    driver: bridge